# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28f1ae0d2947e4cdd689d59d1972e57062e1f9e86e11a6a8795cbb4c24f5c82e8797ab6382c17ce7b7c11b355c48a5d0d8c8f0c3b01f02da89129c0c0a30ab98

test:
  secret_key_base: a10b4050d5d38946f6430f43f4cea5f73e21caea78d7c62cab62b16b6dbfde95695b4bf8947f81908a742aa3a3c0026037724d544c5ca03649ba0430e74ce796

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
